### ISSUE TITLE
Pi-hole / Three Container Setup

### ISSUE THREAD

**Issue by TheDuckMann** [buchdag/letsencrypt-nginx-proxy-companion-compose#9]
Hello Buchdag,

I hope you can help me with this problem. I am using the "three containers/compose-v3/labels"-setup you provided. It is a great setup, thanks to you!
It works fine with other kinds of projects, but when i tried to run Pi-hole behind it, Pi-hole crashed with the following output, even though I'am using the DEFAULT_HOST environment variable:
```
Removing pihole
Recreating d09f715ad0ee_pihole ...
Recreating d09f715ad0ee_pihole ... error

ERROR: for d09f715ad0ee_pihole  Cannot start service pihole: driver failed programming external connectivity on endpoint pihole (f99813b9aca1b4dce45dfc05fc7c52ca6685ea7e0d981e2d557786e3e258a529): Bind for 0.0.0.0:443 failed: port is already allocated

ERROR: for pihole  Cannot start service pihole: driver failed programming external connectivity on endpoint pihole (f99813b9aca1b4dce45dfc05fc7c52ca6685ea7e0d981e2d557786e3e258a529): Bind for 0.0.0.0:443 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```
After trying many different ways of fixing this error, my last attempt was to use the basic/standard "jwilder/nginx-proxy" and et voilà it worked...   :(
So I think I am missing somthing little, but I can't find it. 

My ReverseProxy (based on your example) looks like this:

```yaml
version: '3'
services:
  reverseproxy-nginx:
    image: nginx
    container_name: reverseproxy-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    environment:
      - TZ=Europe/Berlin
    restart: always

  reverseproxy-dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup reverseproxy-nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: reverseproxy-dockergen
    depends_on:
      - reverseproxy-nginx
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    environment:
      - TZ=Europe/Berlin
      - DEFAULT_HOST=pihole.myadress.com
    restart: always

  reverseproxy-letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: reverseproxy-letsencrypt-companion
    depends_on:
      - reverseproxy-nginx
      - reverseproxy-dockergen
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Europe/Berlin
    restart: always

volumes:
  conf:
  vhost:
  html:
  certs:

networks:
  default:
    external:
      name: nginx-reverseproxy
```

My Pi-hole docker-compose.yml looks like this:

```yaml
version: '3'

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - TZ=Europe/Berlin
      - WEBPASSWORD=ReallySecurePasswordForPiHole
      - ServerIP=10.10.10.50
      - VIRTUAL_HOST=pihole.myadress.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=pihole.myadress.com
      - LETSENCRYPT_EMAIL=me@myadress.com
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN
    restart: always

networks:
  default:
    external:
      name: nginx-reverseproxy
```

I would appreciate any hint and/or help.
Thanks in advance!
